### ISSUE TITLE
*tap tap* is this thing on?

### ISSUE THREAD

**Issue by olivermt** [rramsden/sassy#2]
Hello.

Last commit was in 2012, figured I'd ask if this library is even remotely usable still.

I see the underlying C lib is actively maintained so I guess the NIF approach for this should still be sound.
Did you ever use this lib in any kind of production scenario?

You are not listing any kind of license in your repo, can I steal some of your NIF code if I want to make an elixir lib for this?

**Comment by rramsden** [comment]
Hi @olivermt, sorry I missed your comment 😞 I added an MIT license. Feel free to steal any NIF code you need 👍
